"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from growth_machine_sdk_attio_python import utils
from growth_machine_sdk_attio_python.models import (
    put_v2_lists_list_entries_entry_id_op as models_put_v2_lists_list_entries_entry_id_op,
)
from growth_machine_sdk_attio_python.types import BaseModel


class PutV2ListsListEntriesEntryIDNotFoundErrorData(BaseModel):
    status_code: float

    type: models_put_v2_lists_list_entries_entry_id_op.PutV2ListsListEntriesEntryIDNotFoundType

    code: models_put_v2_lists_list_entries_entry_id_op.PutV2ListsListEntriesEntryIDNotFoundCode

    message: str


class PutV2ListsListEntriesEntryIDNotFoundError(Exception):
    r"""Not Found"""

    data: PutV2ListsListEntriesEntryIDNotFoundErrorData

    def __init__(self, data: PutV2ListsListEntriesEntryIDNotFoundErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PutV2ListsListEntriesEntryIDNotFoundErrorData
        )


class PutV2ListsListEntriesEntryIDImmutableValueErrorData(BaseModel):
    status_code: float

    type: models_put_v2_lists_list_entries_entry_id_op.PutV2ListsListEntriesEntryIDBadRequestType

    code: models_put_v2_lists_list_entries_entry_id_op.PutV2ListsListEntriesEntryIDCodeImmutableValue

    message: str


class PutV2ListsListEntriesEntryIDImmutableValueError(Exception):
    r"""Bad Request"""

    data: PutV2ListsListEntriesEntryIDImmutableValueErrorData

    def __init__(self, data: PutV2ListsListEntriesEntryIDImmutableValueErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, PutV2ListsListEntriesEntryIDImmutableValueErrorData
        )
